
["Horns Of War"]
	#Range: 8 ~ 64
	radius = 24
	#Range: 1 ~ 100
	ponderMorale = 40
	#Range: -100 ~ 0
	dreamMorale = -20
	#Range: 40 ~ 99999
	effectDurationTicks = 200
	#Range: 40 ~ 99999
	hornCooldownTicks = 2000

	["Horns Of War".client]
		#Cooldown bar red channel (0–255)
		#Range: 0 ~ 255
		cooldownBarRed = 255
		#Cooldown bar green channel (0–255)
		#Range: 0 ~ 255
		cooldownBarGreen = 170
		#Cooldown bar blue channel (0–255)
		#Range: 0 ~ 255
		cooldownBarBlue = 0

